

PATCH_SIZE = 128
PATCH_OVERLAP = 0.9

PREFIX_LABEL = 'label'
PREFIX_OPT = 'opt'
PREFIX_LIDAR = 'lidar'


DISCARDED_CLASS = 7
REMOVED_CLASSES = [10, 11]
N_CLASSES = 10 - len(REMOVED_CLASSES)
N_OPTICAL_BANDS = 4
N_LIDAR_BANDS = 1#6
"""Bands order: 'BLUE','RED','GREEN','NIR','nx','ny','nz','curvatura','intensity','chm'"""

MAX_EPOCHS = 500



#LEARNING_RATE = 1e-4
LEARNING_RATE = 4e-6
LEARNING_RATE_BETAS = (0.9, 0.999)
LEARNING_RATE_SCHEDULER_GAMMA = 0.5
#LEARNING_RATE_SCHEDULER_MILESTONES = [5, 10, 20, 50]
LEARNING_RATE_SCHEDULER_MILESTONES = [5, 20]

B_W = 0.01
T_W = 0.13
CLASSES_WEIGHTS = [B_W, T_W, T_W, T_W, T_W, T_W, T_W, T_W, T_W, 0]


EARLY_STOP_MIN_EPOCHS = LEARNING_RATE_SCHEDULER_MILESTONES[-1]
EARLY_STOP_PATIENCE = 10
EARLY_STOP_MIN_DELTA = 0.0005

PREDICTION_OVERLAPS = [0, 0.1, 0.3, 0.5, 0.7]
